name: Daily Green Graph

on:
  schedule:
    # Runs every 2 hours (12 commits per day)
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update date file
        run: |
          echo "Commit for $(date)" >> activity_log.txt

      - name: Commit and Push
        run: |
          # Aapki details set kar di gayi hain:
          git config --global user.name "Maheshkrsaw"
          git config --global user.email "maheshkumar9304631853@gmail.com"
          
          git add activity_log.txt
          git commit -m "Automated update: $(date)"
          git push
